name: CI/CD za Frontend in Backend

on:
  push:
    branches:
      - develop
      - SCRUM-75-Webhook

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/frontend
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/veriga-njokov:frontend-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/veriga-njokov:frontend-latest

  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/backend
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/veriga-njokov:backend-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/veriga-njokov:backend-latest
