services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: npm start
    environment:
      - MONGO_URI=mongodb+srv://closy:naj@veriganjokov.tiar0wm.mongodb.net/?retryWrites=true&w=majority&appName=VerigaNjokov
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: